import type { theatre } from "@/types/theatre";

export const airports: {
  NAME: string;
  ICAO: string;
  GROUND: comm;
  TOWER: comm;
  APPR: comm;
  TACAN: string;
  ILS: string[];
  ELEV: string;
  LEN: string;
  ATIS: comm;
  COURSE: string[];
  map: theatre;
}[] = [
  {
    NAME: "Shiraz",
    ICAO: "OISS",
    ATIS: { uhf: "375.550", vhf: "" },
    APPR: { uhf: "344.000", vhf: "" },
    TOWER: { uhf: "275.800", vhf: "" },
    GROUND: { uhf: "", vhf: "" }, // "121.90",
    TACAN: "125X",
    ILS: ["108.50"],
    ELEV: "4927 ft",
    LEN: "14016 ft",
    COURSE: ["292"],
    map: "PG",
  },
  {
    NAME: "RAF AKROTIRI",
    ICAO: "LCRA",
    ATIS: { uhf: "", vhf: "125.000" },
    APPR: { uhf: "235.050", vhf: "" }, //"123.6",
    TOWER: { uhf: "399.850", vhf: "" }, //"130.07",
    GROUND: { uhf: "240.100", vhf: "" }, //"122.12",
    TACAN: "107X",
    ILS: ["109.70"],
    ELEV: "72 ft",
    LEN: "9005 ft",
    COURSE: ["283"],
    map: "Syria",
  },
  {
    NAME: "INCIRLIK AB",
    ICAO: "LTAG",
    ATIS: { uhf: "377.475", vhf: "129.750" },
    APPR: { uhf: "340.775", vhf: "" }, //"118.00",
    TOWER: { uhf: "360.100", vhf: "" }, //"122.10",
    GROUND: { uhf: "371.350", vhf: "" }, //"123.02",
    TACAN: "21X",
    ILS: ["109.30", "111.70"],
    ELEV: "200 ft",
    LEN: "10.000 ft",
    COURSE: ["049", "229"],
    map: "Syria",
  },
  {
    NAME: "HATAY",
    ICAO: "LTDA",
    APPR: { vhf: "118.725", uhf: "" },
    ATIS: { vhf: "", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "121.700", uhf: "" },
    ILS: ["108.90", ""],
    LEN: "",
    TACAN: "74X",
    TOWER: { vhf: "128.525", uhf: "" },
    COURSE: ["039", "216"],
    map: "Syria",
  },
  {
    NAME: "GAZIANTEP",
    ICAO: "LTAJ",
    APPR: { vhf: "119.825", uhf: "" },
    ATIS: { vhf: "", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "121.900", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "",
    TOWER: { vhf: "118.500", uhf: "" },
    COURSE: ["", ""],
    map: "Syria",
  },
  {
    NAME: "GAZIPASA",
    ICAO: "LTFG",
    APPR: { vhf: "119.025", uhf: "" },
    ATIS: { vhf: "120.950", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "121.800", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "",
    TOWER: { vhf: "119.250", uhf: "" },
    COURSE: ["", ""],
    map: "Syria",
  },
  {
    NAME: "ADANA",
    ICAO: "LTAF",
    APPR: { vhf: "130.275", uhf: "340.775" },
    ATIS: { vhf: "119.225", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "122.000", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "",
    TOWER: { vhf: "121.100", uhf: "" },
    COURSE: ["", ""],
    map: "Syria",
  },
  {
    NAME: "RAMAN DAVID",
    ICAO: "LLRD",
    APPR: { vhf: "", uhf: "" },
    ATIS: { vhf: "118.250", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "23X",
    TOWER: { vhf: "119.800", uhf: "" },
    COURSE: ["", ""],
    map: "Syria",
  },
  {
    NAME: "HAIFA",
    ICAO: "LLHA",
    APPR: { vhf: "", uhf: "" },
    ATIS: { vhf: "135.400", uhf: "" },
    ELEV: "20ft",
    GROUND: { vhf: "", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "",
    TOWER: { vhf: "133.000", uhf: "" },
    COURSE: ["", ""],
    map: "Syria",
  },
  {
    NAME: "LARNACA",
    ICAO: "LCLK",
    APPR: { vhf: "130.200", uhf: "" },
    ATIS: { vhf: "126.550", uhf: "" },
    ELEV: "7ft",
    GROUND: { vhf: "119.400", uhf: "" },
    ILS: ["", ""],
    LEN: "",
    TACAN: "",
    TOWER: { vhf: "130.200", uhf: "" },
    COURSE: ["039.7", "219.7"],
    map: "Syria",
  },
  {
    NAME: "BEIRUT",
    ICAO: "OLBA",
    APPR: { vhf: "120.300", uhf: "" },
    ATIS: { vhf: "120.650", uhf: "" },
    ELEV: "",
    GROUND: { vhf: "121.925", uhf: "" },
    ILS: ["108.90", ""],
    LEN: "",
    TACAN: "74X",
    TOWER: { vhf: "118.900", uhf: "" },
    COURSE: ["039", "216"],
    map: "Syria",
  },
  {
    NAME: "GAZIPASA",
    ICAO: "LTFG",
    APPR: { vhf: "119.025", uhf: "" },
    ATIS: { vhf: "120.950", uhf: "" },
    ELEV: "90ft",
    GROUND: { vhf: "121.800", uhf: "" },
    ILS: ["", ""],
    LEN: "2350",
    TACAN: "89X",
    TOWER: { vhf: "119.250", uhf: "" },
    COURSE: ["039", "216"],
    map: "Syria",
  },
];

export const airfieldEmpty: (typeof airports)[0] = {
  NAME: "",
  ICAO: "",
  ATIS: { uhf: "", vhf: "" },
  APPR: { uhf: "", vhf: "" },
  TOWER: { uhf: "", vhf: "" },
  GROUND: { uhf: "", vhf: "" },
  TACAN: "",
  COURSE: [""],
  ILS: [""],
  ELEV: "",
  LEN: "",
  map: "Syria",
};



export type Airport = (typeof airports)[0];

type comm = { uhf: string; vhf: string };
